---
- name: Install required packages
  ansible.builtin.apt:
    name: 
      - chrony
    state: present
  tags:
    - common
    - chrony

- name: Copy Chrony configuration file to controller node
  ansible.builtin.template:
    src: controller-chrony.j2
    dest: /etc/chrony/chrony.conf
    owner: root
    group: root
    mode: '0644'
    backup: true
  when: "'controller' in group_names"
  notify: Restart Chrony
  tags:
    - common
    - chrony

- name: Copy Chrony configuration file not to controller nodes
  ansible.builtin.template:
    src: chrony.j2
    dest: /etc/chrony/chrony.conf
    owner: root
    group: root
    mode: '0644'
    backup: true
  when: "'controller' not in group_names"
  notify: Restart Chrony
  tags:
    - common
    - chrony
