---
# tasks file for rabbitmq
- name: Ensure skyline user is present
  rabbitmq_user: 
    user: skyline
    password: "{{ skyline_rabbit_password }}" 
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present
  tags:
    - skyline
