---
# tasks file for keystone
- name: Create a new database with name 'keystone'
  community.mysql.mysql_db:
    name: keystone
    login_unix_socket: "{{ mysql_socket_path }}"
    state: present

- name: Cretae MySQL keystone user and password using socket
  community.mysql.mysql_user:
    name: keystone
    host: '%'
    password: "{{ mariadb_keystone_password }}"
    priv: 'keystone.*:ALL,GRANT'
    login_unix_socket: "{{ mysql_socket_path }}"
    state: present

- name: Install required packages
  ansible.builtin.apt:
    name:
      - keystone
    state: present

- name: Copy Keystone configuration file to controller node
  ansible.builtin.copy:
    src: keystone.conf 
    dest: /etc/keystone/keystone.conf 
    owner: root
    group: root
    mode: '0644'

- name: Populate the identity service database
  command: su -s /bin/sh -c "keystone-manage db_sync" keystone

- name: Initialize Fernet key repositories fernet_setup
  command: keystone-manage fernet_setup --keystone-user keystone --keystone-group keystone

- name: Initialize Fernet key repositories credential_setup
  command: keystone-manage credential_setup --keystone-user keystone --keystone-group keystone

- name: Bootstrap the Identity service
  command: keystone-manage bootstrap --bootstrap-password "{{ keystone_bootstrap_password }}" --bootstrap-admin-url http://controller-node-01:35357/v3/ --bootstrap-internal-url http://controller-node-01:5000/v3/ --bootstrap-public-url http://controller-node-01:5000/v3/ --bootstrap-region-id RegionOne
