---
# tasks file for images
- name: Check if the OpenStack image CentOS-Stream-GenericCloud-9-latest exists
  ansible.builtin.shell: |
    . /root/.bashrc
    openstack image list --name CentOS-Stream-9-Cloud-Image
  args:
    executable: /bin/sh
  register: image_centos
  changed_when: false
  ignore_errors: yes

- name: Create an OpenStack image CentOS-Stream-GenericCloud-9-latest
  ansible.builtin.shell: |
    . /root/.bashrc
    wget http://cloud.centos.org/centos/9-stream/x86_64/images/CentOS-Stream-GenericCloud-9-latest.x86_64.qcow2
    openstack image create --container-format bare --disk-format qcow2 --file CentOS-Stream-GenericCloud-9-latest.x86_64.qcow2 --public "CentOS-Stream-9-Cloud-Image"
    rm -f CentOS-Stream-GenericCloud-9-latest.x86_64.qcow2
  args:
    executable: /bin/sh
  when: image_centos.stdout == ""

- name: Check if the OpenStack image Ubuntu-22.04-server-cloudimg exists
  ansible.builtin.shell: |
    . /root/.bashrc
    openstack image list --name Ubuntu-22.04-server-cloudimg
  args:
    executable: /bin/sh
  register: image_ubuntu
  changed_when: false
  ignore_errors: yes

- name: Create an OpenStack image Ubuntu-22.04-server-cloudimg-amd64
  ansible.builtin.shell: |
    . /root/.bashrc
    wget https://cloud-images.ubuntu.com/releases/jammy/release/ubuntu-22.04-server-cloudimg-amd64.img
    openstack image create --container-format bare --disk-format qcow2 --file ubuntu-22.04-server-cloudimg-amd64.img --public "Ubuntu-22.04-server-cloudimg"
    rm -f CentOS-Stream-GenericCloud-9-latest.x86_64.qcow2
  args:
    executable: /bin/sh
  when: image_ubuntu.stdout == ""
