---
# tasks file for nova-compute
- name: Install required packages
  ansible.builtin.apt:
    name:
      - nova-compute
    state: present
  register: install_nova_output

- name: Copy Nova configuration file to controller node
  ansible.builtin.template:
    #src: nova.conf
    src: nova.j2
    dest: /etc/nova/nova.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart Nova Compute

- name: Determine whether your compute node supports hardware acceleration for virtual machines
  ansible.builtin.command: egrep -c '(vmx|svm)' /proc/cpuinfo
  register: check_hardware_acceleration
  ignore_errors: yes
  when: install_nova_output.changed|bool == true

- name: Copy Nova Compute configuration file to controller node
  ansible.builtin.template:
    src: nova-compute-qemu.j2
    dest: /etc/nova/nova-compute.conf
    owner: root
    group: root
    mode: '0644'
  when: install_nova_output.changed|bool == true and check_hardware_acceleration.stdout == "0"
  notify: Restart Nova Compute
