---
# tasks file for nova-compute
- name: Install required packages
  ansible.builtin.apt:
    name:
      - nova-compute
    state: present
  register: install_nova_output

- name: Copy Nova configuration file to controller node
  ansible.builtin.copy:
    src: nova.conf
    dest: /etc/nova/nova.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart Nova Compute

- name: Copy Nova Compute configuration file to controller node
  ansible.builtin.copy:
    src: nova-compute.conf
    dest: /etc/nova/nova-compute.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart Nova Compute
