---
# tasks file for nova-compute
- name: Install required packages
  ansible.builtin.apt:
    name:
      - nova-compute
      - neutron-openvswitch-agent
    state: present
  register: install_nova_output

- name: Create a bridge named br-ex for the external network
  ansible.builtin.shell: |
    ovs-vsctl add-br br-ex
    ovs-vsctl add-port br-ex enX1
  when: install_nova_output.changed|bool == true

- name: Copy Nova configuration file to controller node
  ansible.builtin.template:
    #src: nova.conf
    src: nova.j2
    dest: /etc/nova/nova.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart Nova Compute

- name: Determine whether your compute node supports hardware acceleration for virtual machines
  ansible.builtin.command: egrep -c '(vmx|svm)' /proc/cpuinfo
  register: check_hardware_acceleration
  ignore_errors: yes
  when: install_nova_output.changed|bool == true

- name: Copy Nova Compute configuration file
  ansible.builtin.template:
    src: nova-compute-qemu.j2
    dest: /etc/nova/nova-compute.conf
    owner: root
    group: root
    mode: '0644'
  when: install_nova_output.changed|bool == true and check_hardware_acceleration.stdout == "0"
  notify: Restart Nova Compute

- name: Copy Neutron Server configuration file
  ansible.builtin.template:
    src: neutron.j2
    dest: /etc/neutron/neutron.conf
    owner: root
    group: root
    mode: '0644'
  when: install_nova_output.changed|bool == true and check_hardware_acceleration.stdout == "0"
  notify: Restart Neutron Openvswitch Agent

- name: Copy Neutron Openvswitch Agent configuration file
  ansible.builtin.template:
    src: openvswitch_agent.j2
    dest: /etc/neutron/plugins/ml2/openvswitch_agent.ini
    owner: root
    group: root
    mode: '0644'
#  when: install_nova_output.changed|bool == true and check_hardware_acceleration.stdout == "0"
  notify: Restart Neutron Openvswitch Agent


- name: Discover compute hosts
  ansible.builtin.shell: |
     su -s /bin/sh -c "nova-manage cell_v2 discover_hosts --verbose" nova
  args:
    executable: /bin/sh
