---
# tasks file for rabbitmq
- name: Install required packages
  ansible.builtin.apt:
    name:
      - rabbitmq-server
    state: present
  tags:
    - rabbitmq-server

- name: Copy Rabbitmq configuration file to controller node
  ansible.builtin.template:
    src: rabbitmq-env.j2
    dest: /etc/rabbitmq/rabbitmq-env.conf
    owner: root
    group: root
    mode: '0644'
    backup: true
  notify: Restart Rabbitmq
  tags:
    - rabbitmq-server

- name: Ensure anonymous guest user is absent
  ansible.builtin.rabbitmq_user: 
    user: guest 
    state: absent
  tags:
    - rabbitmq-server
