---
# tasks file for nova-controller
- name: Install required packages
  ansible.builtin.apt:
    name:
      - nova-api 
      - nova-conductor 
      - nova-novncproxy 
      - nova-scheduler
    state: present
  register: install_nova_output

- name: Copy Nova configuration file to controller node
  ansible.builtin.template:
    src: nova.j2
    dest: /etc/nova/nova.conf
    owner: root
    group: root
    mode: '0644'
  notify:
    - Restart Nova API 
    - Restart Nova Scheduler
    - Restart Nova Conductor
    - Restart Nova Novncproxy

- name: Populate the nova-api database
  ansible.builtin.command: su -s /bin/sh -c "nova-manage api_db sync" nova

- name: Register the cell0 database
  ansible.builtin.command: su -s /bin/sh -c "nova-manage cell_v2 map_cell0" nova

- name: Create the cell1 cell
  ansible.builtin.command: su -s /bin/sh -c "nova-manage cell_v2 create_cell --name=cell1 --verbose" nova

- name: Populate the nova database
  ansible.builtin.command: su -s /bin/sh -c "nova-manage db sync" nova
