#SPDX-License-Identifier: MIT-0
---
# tasks file for memcached
- name: Install required packages
  ansible.builtin.apt:
    name:
      - memcached 
      - python3-memcache
    state: present

- name: Copy Memcached configuration file to controller node
  ansible.builtin.template:
    src: memcached.j2
    dest: /etc/memcached.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart Memcached
