---
- name: Install or verify database
  hosts: controller
  become: true
  vars_files:
    - ../../vaults.yml
  roles:
    - mariadb

- name: Configure RabbitMQ server
  hosts: controller
  become: true
  vars_files:
    - ../../vaults.yml
  roles:
    - rabbitmq

- name: Set or verify Keystone config
  hosts: controller
  become: true
  vars_files:
    - ../../vaults.yml
  roles:
    - keystone

- name: Set up the OpenStack Compute nova (controller node)
  hosts: controller
  become: true
  vars_files:
    - ../../vaults.yml
  roles:
    - controller

- name: Set up the OpenStack Compute nova (compute node)
  hosts: computes
  become: true
  vars_files:
    - ../../vaults.yml
  roles:
    - compute

- name: Finalize installation the OpenStack Compute nova
  hosts: controller
  become: true
  vars_files:
    - ../../vaults.yml
  roles:
    - compute-finalize

- name: Define the compute, memory, and storage capacity of computing instances
  hosts: controller
  become: true
  vars_files:
    - ../../vaults.yml
  roles:
    - flavors
