#SPDX-License-Identifier: MIT-0
---
- name: Install required packages
  ansible.builtin.apt:
    name: 
      - chrony
    state: present

- name: Copy Chrony configuration file to controller node
  ansible.builtin.template:
    src: controller-chrony.j2
    dest: /etc/chrony/chrony.conf
    owner: root
    group: root
    mode: '0644'
  when: "'controller' in group_names"
  notify: Restart Chrony

- name: Copy Chrony configuration file to compute nodes
  ansible.builtin.template:
    src: compute-chrony.j2
    dest: /etc/chrony/chrony.conf
    owner: root
    group: root
    mode: '0644'
  when: "'computes' in group_names"
  notify: Restart Chrony
