#SPDX-License-Identifier: MIT-0
---
- name: Install required packages
  ansible.builtin.apt:
    name: 
      - chrony
    state: present

- name: Copy Chrony configuration file to controller node
  ansible.builtin.copy:
    src: controller-node-chrony.conf
    dest: /etc/chrony/chrony.conf
    owner: root
    group: root
    mode: '0644'
  when: "'controller' in group_names"
  notify: Restart Chrony

- name: Copy Chrony configuration file to compute nodes
  ansible.builtin.copy:
    src: compute-nodes-chrony.conf
    dest: /etc/chrony/chrony.conf
    owner: root
    group: root
    mode: '0644'
  when: "'compute' in group_names"
  notify: Restart Chrony
