---
# tasks file for skyline
- name: Install required packages
  ansible.builtin.apt:
    name:
      - docker.io
    state: present
  tags:
    - skylinie

- name: Create the skyline directory if it does not exist
  ansible.builtin.file:
    path: "{{ item }}"
    mode: '0644'
    state: directory
  with_items:
    - /etc/skyline
    - /tmp/skyline
    - /var/log/skyline
  tags:
    - skylinie

- name: Copy Dashboard configuration file to controller node
  ansible.builtin.template:
    src: skyline.j2
    dest: /etc/skyline/skyline.yaml
    owner: root
    group: root
    mode: '0644'
    backup: true
  tags:
    - skyline
