---
# tasks file for nova-compute-finalize
- name: Pause for 1 minute
  ansible.builtin.pause:
    seconds: 30

- name: Discover compute hosts
  ansible.builtin.shell: |
     su -s /bin/sh -c "nova-manage cell_v2 discover_hosts --verbose" nova
  args:
    executable: /bin/sh
