---
# tasks file for ceilometer
- name: Install required packages
  ansible.builtin.apt:
    name:
      - gnocchi-api 
      - gnocchi-metricd 
      - python3-gnocchiclient 
      - uwsgi-plugin-python3 
      - uwsgi
      - ceilometer-agent-notification 
      - ceilometer-agent-central 
    state: present
  tags:
    - monitoring-services
    - ceilometer

- name: Copy the Gnocchi configuration file to controller node
  ansible.builtin.template:
    src: gnocchi.j2
    dest: /etc/gnocchi/gnocchi.conf
    owner: root
    group: root
    mode: '0644'
    backup: true
  tags:
    - monitoring-services
    - ceilometer

- name: Gnocchi Upgrade
  ansible.builtin.command: su -s /bin/sh -c gnocchi-upgrade
  tags:
    - monitoring-services
    - ceilometer
