---
# tasks file for heat
- name: Install required packages
  ansible.builtin.apt:
    name:
      - heat-api 
      - heat-api-cfn 
      - heat-engine
    state: present
  tags:
    - orchestration
    - heat

- name: Copy the Heat configuration file to controller node
  ansible.builtin.template:
    src: heat.j2
    dest: /etc/heat/heat.conf 
    owner: root
    group: root
    mode: '0644'
    backup: true
  notify:
    - Restart Heat API
    - Restart Heat API CFG
    - Restart Heat Engine
  tags:
    - orchestration
    - heat

- name: Populate the database
  ansible.builtin.command: su -s /bin/sh -c "heat-manage db_sync" heat
  tags:
    - orchestration
    - heat
