---
- name: Setup steps that are not specific to a particular role or project
  hosts: all
  become: true
  roles:
    - all

- name: Set up the Network Time Protocol (NTP) client and server
  hosts: all
  become: true
  roles:
    - chrony

- name: Set up the in-memory key-value store system
  hosts: controller
  become: true
  roles:
    - memcached

#- name: Set up the strongly consistent key-value store
#  hosts: controller
#  become: true
#  roles:
#    - etcd

- name: Set up the message broker
  hosts: controller
  become: true
  roles:
    - rabbitmq

- name: Set up the community-developed relational database
  hosts: controller
  become: true
  roles:
    - mariadb
