---
# tasks file for flavors
- name: Create the flavor m1.tiny
  openstack.cloud.compute_flavor:
    cloud: "{{ openstack_auth }}"
    name: m1.tiny
    ram: 1024
    swap: 1024 
    vcpus: 1
    disk: 8
    state: present
  tags:
    - nova

- name: Create the flavor m1.small
  openstack.cloud.compute_flavor:
    cloud: "{{ openstack_auth }}"
    name: m1.small
    ram: 2048
    swap: 2048
    vcpus: 1
    disk: 8
    state: present
  tags:
    - nova

- name: Create the flavor m1.medium
  openstack.cloud.compute_flavor:
    cloud: "{{ openstack_auth }}"
    name: m1.medium
    ram: 4096
    swap: 2048
    vcpus: 1
    disk: 8
    state: present
  tags:
    - nova

- name: Create the flavor m1.large
  openstack.cloud.compute_flavor:
    cloud: "{{ openstack_auth }}"
    name: m1.large
    ram: 8192
    swap: 2048
    vcpus: 2
    disk: 16
    state: present
  tags:
    - nova

- name: Create the flavor m1.xlarge
  openstack.cloud.compute_flavor:
    cloud: "{{ openstack_auth }}"
    name: m1.xlarge
    ram: 16384
    swap: 2048
    vcpus: 4
    disk: 16
    state: present
  tags:
    - nova

- name: Create the flavor m1.2xlarge
  openstack.cloud.compute_flavor:
    cloud: "{{ openstack_auth }}"
    name: m1.xlarge
    ram: 32768
    swap: 4096
    vcpus: 8
    disk: 32
    state: present
  tags:
    - nova
