#SPDX-License-Identifier: MIT-0
---
# tasks file for common
- name: Disable UFW firewall
  community.general.ufw:
    state: disabled

- name: Execute add-apt-repository for cloud-archive:epoxy
  ansible.builtin.shell: |
    add-apt-repository -y cloud-archive:epoxy
  args:
    creates: /etc/apt/sources.list.d/cloudarchive-epoxy.list

- name: Update apt cache and upgrade packages
  ansible.builtin.apt:
    update_cache: yes
    upgrade: yes
  tags:
    - common

- name: Update hostnames
  hostname:
    name: "{{ ansible_host_name }}"
  tags:
    - common

- name: Add IP address of all hosts to all hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ item }}$'
    line: "{{ hostvars[item].ansible_host }} {{ item }}"
    state: present
  when: hostvars[item].ansible_host is defined
  with_items: "{{ groups.cluster }}"
  tags:
    - common

- name: Install required packages
  ansible.builtin.apt:
    name: 
      - vim
      - curl
      - wget
      - telnet
      - locales
      - dnsutils
      - net-tools
    state: present
  tags:
    - common
    - locale

- name: Install openstackclient
  ansible.builtin.apt:
    name:
      - python3-openstackclient
    state: present
  when: "'controller' in group_names"
  tags:
    - common
    - locale
