---
# tasks file for nova-controller
- name: Create a new database with name 'nova'
  community.mysql.mysql_db:
    name: nova
    login_unix_socket: "{{ mysql_socket_path }}"
    state: present

- name: Create a new database with name 'nova_api'
  community.mysql.mysql_db:
    name: nova_api
    login_unix_socket: "{{ mysql_socket_path }}"
    state: present

- name: Create a new database with name 'nova_cell0'
  community.mysql.mysql_db:
    name: nova_cell0
    login_unix_socket: "{{ mysql_socket_path }}"
    state: present

- name: Cretae MySQL Nova user and password using socket
  community.mysql.mysql_user:
    name: nova
    host: '%'
    password: "{{ mariadb_nova_password }}"
    priv: 
      'nova.*': 'ALL,GRANT'
      'nova_api.*': 'ALL,GRANT'
      'nova_cell0.*': 'ALL,GRANT'
    login_unix_socket: "{{ mysql_socket_path }}"
    state: present

- name: Install required packages
  ansible.builtin.apt:
    name:
      - nova-api 
      - nova-conductor 
      - nova-novncproxy 
      - nova-scheduler
    state: present
  register: install_nova_output

- name: Copy Nova configuration file to controller node
  ansible.builtin.template:
    src: nova.j2
    dest: /etc/nova/nova.conf
    owner: root
    group: root
    mode: '0644'
  notify:
    - Restart Nova API 
    - Restart Nova Scheduler
    - Restart Nova Conductor
    - Restart Nova Novncproxy

- name: Configure User and Endpoints
  ansible.builtin.shell: |
    . /root/.bashrc
    openstack user create --domain default --password {{ mariadb_nova_password }} nova
    openstack role add --project admin --user nova admin
    openstack service create --name nova --description "OpenStack Compute" compute
  args:
    executable: /bin/sh
  when: install_nova_output.changed|bool == true

- name: Create the Placement API service endpoints
  ansible.builtin.shell: |
    . /root/.bashrc
    openstack endpoint create --region RegionOne compute public http://controller:8774/v2.1
    openstack endpoint create --region RegionOne compute internal http://controller:8774/v2.1
    openstack endpoint create --region RegionOne compute admin http://controller:8774/v2.1
  args:
    executable: /bin/sh
  when: install_nova_output.changed|bool == true

- name: Populate the nova-api database
  ansible.builtin.command: su -s /bin/sh -c "nova-manage api_db sync" nova
  when: mysql_db_output.changed|bool == true and install_nova_output.changed|bool == true

- name: Register the cell0 database
  ansible.builtin.command: su -s /bin/sh -c "nova-manage cell_v2 map_cell0" nova
  when: mysql_db_output.changed|bool == true and install_nova_output.changed|bool == true

- name: Create the cell1 cell
  ansible.builtin.command: su -s /bin/sh -c "nova-manage cell_v2 create_cell --name=cell1 --verbose" nova
  when: mysql_db_output.changed|bool == true and install_nova_output.changed|bool == true

- name: Populate the nova database
  ansible.builtin.command: su -s /bin/sh -c "nova-manage db sync" nova
  when: mysql_db_output.changed|bool == true and install_nova_output.changed|bool == true
