---
# tasks file for keystone
- name: Create the new OpenStack user
  openstack.cloud.identity_user:
    cloud: "{{ openstack_auth }}"
    name: "nova"
    password: "{{ nova_identity_password }}"
    description: "OpenStack nova user"
    domain: default
    state: present
  tags:
    - nova

- name: Grant an admin role on the user in the project
  openstack.cloud.role_assignment:
    cloud: "{{ openstack_auth }}"
    user: nova
    role: admin
    project: "{{ project_name }}"
    state: present
  tags:
    - nova

- name: Create a new service
  openstack.cloud.catalog_service:
     cloud: "{{ openstack_auth }}"
     name: nova
     type: compute
     description: "OpenStack Compute Service"
     state: present
  tags:
    - nova

- name: Create an endpoint
  openstack.cloud.endpoint:
     cloud: "{{ openstack_auth }}"
     service: nova
     endpoint_interface: "{{ item }}"
     url: http://controller:8774/v2.1
     region: RegionOne
     state: present
  with_items:
    - public
    - internal
    - admin
  tags:
    - nova
