---
# tasks file for mariadb
- name: Ensure glance database is present
  community.mysql.mysql_db:
    name: glance
    login_unix_socket: "{{ mysql_socket_path }}"
  tags:
    - shared-services
    - glance
    - mariadb

- name: Ensure glance database user is present
  community.mysql.mysql_user:
    name: glance
    host: "{{ item }}"
    password: "{{ glance_mariadb_password }}"
    priv: glance.*:ALL
    login_unix_socket: "{{ mysql_socket_path }}"
  with_items:
    - "%"
    - localhost
  tags:
    - shared-services
    - glance
    - mariadb
