---
# tasks file for glance
- name: Create a new database with name 'glance'
  community.mysql.mysql_db:
    name: glance
    login_unix_socket: "{{ mysql_socket_path }}"
    state: present

- name: Cretae MySQL Glance user and password using socket
  community.mysql.mysql_user:
    name: glance
    host: '%'
    password: "{{ mariadb_glance_password }}"
    priv:
      'glance.*': 'ALL,GRANT'
    login_unix_socket: "{{ mysql_socket_path }}"
    state: present

- name: Install required packages
  ansible.builtin.apt:
    name:
      - glance
    state: present

- name: Copy glance-api configuration file to controller node
  ansible.builtin.copy:
    src: glance-api.conf
    dest: /etc/glance/glance-api.conf
    owner: root
    group: root
    mode: '0644'
  register: copy_config_output

#- name: Populate the Image service database
#  command: su -s /bin/sh -c "keystone-manage db_sync" keystone
#  when: copy_config_output.changed|bool == true
