---
# tasks file for rabbitmq
- name: Ensure nova vhost is present
  rabbitmq_vhost: 
    name: /nova
    state: present
  tags:
    - nova

- name: Ensure nova user is present
  rabbitmq_user: 
    user: nova
    password: "{{ nova_rabbit_password }}" 
    vhost: /nova
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present
  tags:
    - nova
