---
# handlers file for heat
- name: Restart Gnocchi API
  ansible.builtin.systemd:
    name: gnocchi-api
    enabled: true
    state: restarted

- name: Restart Gnocchi Metricd
  ansible.builtin.systemd:
    name: gnocchi-metricd
    enabled: true
    state: restarted
