---
# tasks file for magnum
- name: Install required packages
  ansible.builtin.apt:
    name:
      - magnum-api 
      - magnum-conductor 
      - python3-magnumclient
    state: present
  register: install_magnum_output

- name: Copy the Magnum configuration file to controller node
  ansible.builtin.template:
    src: magnum.j2
    dest: /etc/magnum/magnum.conf
    owner: root
    group: root
    mode: '0644'
    backup: true
  notify:
    - Restart Magnum API Services
    - Restart Magnum Conductor Services

- name: Populate the database
  ansible.builtin.command: su -s /bin/sh -c "magnum-db-manage upgrade" magnum
