---
# tasks file for keystone
- name: Create the new OpenStack user
  openstack.cloud.identity_user:
    cloud: "{{ openstack_auth }}"
    name: "cinder"
    password: "{{ cinder_identity_password }}"
    description: "OpenStack cinder user"
    domain: default
    state: present
  tags:
    - storage
    - cinder
    - keystone

- name: Grant an admin role on the user in the project
  openstack.cloud.role_assignment:
    cloud: "{{ openstack_auth }}"
    user: cinder
    role: admin
    project: "{{ project_name }}"
    state: present
  tags:
    - storage
    - cinder
    - keystone

- name: Create a new service cinder
  openstack.cloud.catalog_service:
     cloud: "{{ openstack_auth }}"
     name: volumev3
     type: volumev3
     description: "OpenStack Block Storage"
     state: present
  tags:
    - storage
    - cinder
    - keystone

- name: Create an endpoint cinder
  openstack.cloud.endpoint:
     cloud: "{{ openstack_auth }}"
     service: volumev3
     endpoint_interface: "{{ item }}"
     url: http://controller:8776/v3/%(project_id)s
     region: RegionOne
     state: present
  with_items:
    - public
    - internal
    - admin
  tags:
    - storage
    - cinder
    - keystone
