---
# tasks file for neutron
- name: Create a new database with name 'neutron'
  community.mysql.mysql_db:
    name: neutron
    login_unix_socket: "{{ mysql_socket_path }}"
    state: present
  register: mysql_db_output

- name: Cretae MySQL Neutron user and password using socket
  community.mysql.mysql_user:
    name: neutron
    host: '%'
    password: "{{ mariadb_neutron_password }}"
    priv:
      'neutron.*': 'ALL,GRANT'
    login_unix_socket: "{{ mysql_socket_path }}"
    state: present

- name: Install required packages
  ansible.builtin.apt:
    name:
      - neutron-server 
      - neutron-plugin-ml2
      - neutron-openvswitch-agent 
      - neutron-dhcp-agent
      - neutron-metadata-agent
#      - neutron-l3-agent 
    state: present
  register: install_neutron_output

- name: Copy neutron configuration file to controller node
  ansible.builtin.copy:
    src: neutron.conf
    dest: /etc/neutron/neutron.conf
    owner: root
    group: root
    mode: '0644'
  notify:
    - Restart Nova API
    - Restart Neutron Server
    - Restart Neutron Openvswitch Agent
    - Restart Neutron DHCP Agent
    - Restart Neutron Metadata Agent
#    - Restart Neutron L3 Agent

- name: Copy ml2 configuration file to controller node
  ansible.builtin.copy:
    src: ml2_conf.ini
    dest: /etc/neutron/plugins/ml2/ml2_conf.ini
    owner: root
    group: root
    mode: '0644'
  notify:
    - Restart Nova API
    - Restart Neutron Server
    - Restart Neutron Openvswitch Agent
    - Restart Neutron DHCP Agent
    - Restart Neutron Metadata Agent
#    - Restart Neutron L3 Agent

- name: Copy metadata agent configuration file to controller node
  ansible.builtin.copy:
    src: metadata_agent.ini
    dest: /etc/neutron/metadata_agent.ini
    owner: root
    group: root
    mode: '0644'
  notify:
    - Restart Nova API
    - Restart Neutron Server
    - Restart Neutron Openvswitch Agent
    - Restart Neutron DHCP Agent
    - Restart Neutron Metadata Agent
#    - Restart Neutron L3 Agent

- name: Configure User and Endpoints
  ansible.builtin.shell: |
    . /root/.bashrc
    openstack user create --domain default --password {{ mariadb_neutron_password }} neutron
    openstack role add --project admin --user neutron admin
    openstack service create --name neutron --description "OpenStack Networking" network
  args:
    executable: /bin/sh
  when: install_neutron_output.changed|bool == true

- name: Create the Placement API service endpoints
  ansible.builtin.shell: |
    . /root/.bashrc
    openstack endpoint create --region RegionOne network public http://controller:9696
    openstack endpoint create --region RegionOne network internal http://controller:9696
    openstack endpoint create --region RegionOne network admin http://controller:9696
  args:
    executable: /bin/sh
  when: install_neutron_output.changed|bool == true

- name: Populate the database
  ansible.builtin.command: su -s /bin/sh -c "neutron-db-manage --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/plugins/ml2/ml2_conf.ini upgrade head" neutron
  when: mysql_db_output.changed|bool == true and install_neutron_output.changed|bool == true
