---
# tasks file for rabbitmq
- name: Ensure neutron user is present
  rabbitmq_user: 
    user: neutron
    password: "{{ neutron_rabbit_password }}" 
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present
  tags:
    - neutron
