---
# tasks file for keystone
- name: Create the new OpenStack user
  openstack.cloud.identity_user:
    cloud: "{{ openstack_auth }}"
    name: "neutron"
    password: "{{ neutron_identity_password }}"
    description: "OpenStack neutron user"
    domain: default
    state: present
  tags:
    - networking
    - neutron
    - keystone

- name: Grant an admin role on the user in the project
  openstack.cloud.role_assignment:
    cloud: "{{ openstack_auth }}"
    user: neutron
    role: admin
    project: "{{ project_name }}"
    state: present
  tags:
    - networking
    - neutron
    - keystone

- name: Create a new service
  openstack.cloud.catalog_service:
     cloud: "{{ openstack_auth }}"
     name: neutron
     type: network
     description: "OpenStack Image Service"
     state: present
  tags:
    - networking
    - neutron
    - keystone

- name: Create an endpoint
  openstack.cloud.endpoint:
     cloud: "{{ openstack_auth }}"
     service: neutron
     endpoint_interface: "{{ item }}"
     url: http://controller:9696
     region: RegionOne
     state: present
  with_items:
    - public
    - internal
    - admin
  tags:
    - networking
    - neutron
    - keystone
